<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
     
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
		<link rel="stylesheet" href="/<?php echo SITE_NAME; ?>/css/styles.css" type="text/css">
		<link rel="stylesheet" href="/<?php echo SITE_NAME; ?>/css/login.css" type="text/css"></link>
		<link rel="stylesheet" href="/<?php echo SITE_NAME; ?>/css/login/login.css" type="text/css"></link>
		<link rel="icon" image/x-icon href="/<?php echo SITE_NAME; ?>/css/sources/favicon.ico" />
		
	</head>  
	<body>

	
